variables:
  HOST: "gohala.com"
  USERNAME: "developer@gohala.com"
  PASSWORD: "U0iyBQstz"

deploy:
  script:
    - apt-get update -qq && apt-get install -y -qq lftp
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; mirror -Rnev ./ --ignore-time --parallel=10 --exclude-glob .git* --exclude .env --exclude .git/ --exclude \.gitlab-ci.yml --exclude \vendor/* --exclude \storage/*"
  only:
    - ftp
